name: Gallery (Compat) CI

on:
 push:
  branches:
   - v1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Load Maps Token
      env: 
        MAPS_TOKEN: $
      run: echo MAPS_TOKEN=\"$MAPS_TOKEN\" > ./api.properties
    - name: Build Compat Release APK
      run: ./gradlew assembleCompatRelease
    - uses: actions/upload-artifact@v3
      with:
        name: Gallery-compat.apk
        path: app/compat/release/app-compat-release.apk